apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "emreemre123"  
        - name: MYSQL_DATABASE
          value: "mysqldatabase"  
        - name: MYSQL_USER
          value: "admin"  
        - name: MYSQL_PASSWORD
          value: "adminadmin123"  