apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service"
        - name: WORDPRESS_DB_USER
          value: "admin"  
        - name: WORDPRESS_DB_PASSWORD
          value: "adminadmin123"  
        - name: WORDPRESS_DB_NAME
          value: "mysqldatabase"  
